import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FaChrome, FaGithub } from "react-icons/fa";
import Menu from '../components/Menu'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Menu/>
        <div className='main-div'>

          <div className='hero'>
            <div className='slider'>
              <div id="carouselExampleControls" className="carousel slide" data-bs-ride="carousel">
                <div className="carousel-inner">
                  <div className="carousel-item active">
                    <img src="/assets/1.png" className="d-block w-100" alt="..." />
                  </div>
                  <div className="carousel-item">
                    <img src="/assets/2.png" className="d-block w-100" alt="..." />
                  </div>
                  <div className="carousel-item">
                    <img src="/assets/3.png" className="d-block w-100" alt="..." />
                  </div>
                  <div className="carousel-item">
                    <img src="/assets/4.png" className="d-block w-100" alt="..." />
                  </div>
                  <div className="carousel-item">
                    <img src="/assets/5.png" className="d-block w-100" alt="..." />
                  </div>
                </div>

                <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span className="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span className="visually-hidden">Previous</span>
                </button>
                <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span className="carousel-control-next-icon" aria-hidden="true"></span>
                  <span className="visually-hidden">Next</span>
                </button>
              </div>
            </div>

            <div className='hero-main-text'>
              <h1>Litescribe Wallet</h1>
              <h2>Open Source Chrome Extension for Litecoin Ordinals & LTC-20</h2>
              <div>
                <div className='points'>
                  <div>
                    <div className='mark-1' /> <div>Store and transfer your Ordinals NFTs</div>
                  </div>
                  <div>
                    <div className='mark-2' /> <div>100% Open-source (GitHub)</div>
                  </div>
                  <div>
                    <div className='mark-3' /> <div>Inscribe on-the-fly without running a fullnode</div>
                  </div>
                  <div>
                    <div className='mark-4' /> <div>Store, mint and transfer LTC-20</div>
                  </div>
                </div>
              </div>

              <div className='btn-group'>
                <button> Download from Chrome Store <FaChrome /></button>
                <button> Download from Github <FaGithub /></button>
              </div>
            </div>

            <div className='bg' />

          </div>

          <div className='faqs'>

              <h1>Frequently Asked Questions</h1>
            <div className='faqs-div'>

              <div className="accordion accordion-flush" id="accordionFlushExample">
                <div className="accordion-item">
                  <h2 className="accordion-header" id="flush-headingOne">
                    <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                    What is Litescribe?
                    </button>
                  </h2>
                  <div id="flush-collapseOne" className="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div className="accordion-body"> is a service that allows users to inscribe data onto the Litecoin blockchain using the Ordinal Protocol. Litescribe uses the same principles and rules of the Ordinal Protocol but applies them specifically to the Litecoin network instead of Bitcoin.
                    </div>
                  </div>
                </div>
                <div className="accordion-item">
                  <h2 className="accordion-header" id="flush-headingTwo">
                    <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                    What is Litescribe?
                    </button>
                  </h2>
                  <div id="flush-collapseTwo" className="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                    <div className="accordion-body"> is a service that allows users to inscribe data onto the Litecoin blockchain using the Ordinal Protocol. Litescribe uses the same principles and rules of the Ordinal Protocol but applies them specifically to the Litecoin network instead of Bitcoin.
                    </div>
                  </div>
                </div>
                <div className="accordion-item">
                  <h2 className="accordion-header" id="flush-headingThree">
                    <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    What is Litescribe?
                    </button>
                  </h2>
                  <div id="flush-collapseThree" className="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                    <div className="accordion-body"> is a service that allows users to inscribe data onto the Litecoin blockchain using the Ordinal Protocol. Litescribe uses the same principles and rules of the Ordinal Protocol but applies them specifically to the Litecoin network instead of Bitcoin.
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>

          <div className='footer'>
            <div>litescribe</div>
            <div>All rights reserved</div>

          </div>
        </div>
      </main>
    </>
  )
}
